# Host to use for canonical URL generation (without trailing slash)
host: https://gds-way.cloudapps.digital
service_link: /

# Header-related options
show_govuk_logo: false
service_name: The GDS Way
description: Technical standards and guidance used by teams building software at GDS

# Links to show on right-hand-side of header
header_links:
  GitHub: https://github.com/alphagov/gds-way

footer_links: 
  Accessibility: /accessibility.html

enable_search: true

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
# ga_tracking_id: UA-111409592-1

# Table of contents depth â€“ how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 6

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false

show_contribution_banner: true
github_repo: alphagov/gds-way
github_branch: main

# Ownership for page reviews
default_owner_slack: '#gds-way'
owner_slack_workspace: gds

redirects:
  /standards/publish-opensource-code.html: /standards/source-code.html#publish-open-source-code
  /standards/git.html: /standards/source-code.html#working-with-git
  /standards/cyber-security-overview.html: /standards/cdio-pillars.html#cdio-security
  /standards/reliability-engineering.html: /standards/cdio-pillars.html#reliability-engineering
  /standards/testing-with-rspec.html: /manuals/programming-languages/ruby.html#testing-with-rspec
  /standards/technical-operations.html: /standards/cdio-pillars.html
  /standards/secrets-ACL.html: /standards/secrets-acl.html
